const icons = import.meta.glob<string>("./icons/vivid/*.svg", {
  eager: true,
  query: "?url",
  import: "default",
});
const byExtension: Record<string, string> = {
  pdf: "pdf",
  doc: "doc",
  docx: "docx",
  odt: "docx",
  rtf: "doc",
  xls: "xls",
  xlsx: "xlsx",
  ods: "xlsx",
  csv: "csv",
  ppt: "ppt",
  pptx: "pptx",
  odp: "pptx",
  txt: "txt",
  md: "md",
  markdown: "md",
  json: "json",
  xml: "xml",
  yaml: "txt",
  yml: "txt",
  html: "html",
  htm: "html",
  css: "css",
  js: "js",
  mjs: "js",
  cjs: "js",
  ts: "ts",
  jsx: "js",
  tsx: "ts",
  py: "py",
  java: "java",
  sql: "sql",
  zip: "zip",
  rar: "rar",
  "7z": "7z",
  tar: "tar",
  gz: "gz",
  mp3: "mp3",
  wav: "wav",
  m4a: "mp3",
  aac: "mp3",
  ogg: "mp3",
  mp4: "mp4",
  mov: "mov",
  webm: "mp4",
  avi: "mov",
  jpg: "jpg",
  jpeg: "jpeg",
  png: "png",
  gif: "gif",
  svg: "svg",
  exe: "exe",
  dmg: "dmg",
};
const byMime: Record<string, string> = {
  "application/pdf": "pdf",
  "application/msword": "doc",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
  "application/vnd.ms-excel": "xls",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "text/csv": "csv",
  "application/csv": "csv",
  "application/vnd.ms-powerpoint": "ppt",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
  "text/plain": "txt",
  "text/markdown": "md",
  "application/json": "json",
  "application/xml": "xml",
  "text/xml": "xml",
  "text/html": "html",
  "text/css": "css",
  "text/javascript": "js",
  "application/javascript": "js",
  "application/typescript": "ts",
  "application/zip": "zip",
  "application/x-7z-compressed": "7z",
  "application/x-rar-compressed": "rar",
  "audio/mpeg": "mp3",
  "audio/mp3": "mp3",
  "audio/wav": "wav",
  "audio/x-wav": "wav",
  "audio/aac": "mp3",
  "video/mp4": "mp4",
  "video/quicktime": "mov",
  "image/jpeg": "jpeg",
  "image/png": "png",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "application/x-msdownload": "exe",
  "application/x-apple-diskimage": "dmg",
};
export function fileIconName(name: string, mime: string): string {
  const extension = name.split(/[\\/]/).pop()?.split(".").pop()?.toLowerCase() ?? "";
  const type = mime.toLowerCase().split(";")[0]!.trim();
  if (type === "application/octet-stream" || type === "")
    return byExtension[extension] ?? "txt";
  return byMime[type] ?? byExtension[extension] ?? "txt";
}
export function fileIconFor(name: string, mime: string): string {
  const icon = fileIconName(name, mime);
  return icons[`./icons/vivid/${icon}.svg`] ?? icons["./icons/vivid/txt.svg"]!;
}
