import { expect, test } from '@playwright/test'
import { signIn } from './login'

test('compact project list and plain project chats retain keyboard and menu access', async ({ page }, testInfo) => {
  await page.setViewportSize(testInfo.project.name === 'mobile' ? { width: 390, height: 844 } : { width: 1280, height: 900 })
  await signIn(page, '/chathermes?view=projects')
  const plugin = page.locator('.chathermes-embedded')
  const projects = plugin.locator('.project-list')
  await expect(plugin.getByRole('button', { name: 'New project', exact: true })).toBeVisible()
  await expect(plugin.locator('.project-chats-heading')).toHaveCount(0)
  await expect(plugin.locator('.projects-page').getByRole('button', { name: 'New chat', exact: true })).toHaveCount(0)
  const project = projects.getByRole('button', { name: 'Hermes Mobile', exact: true })
  const height = await project.evaluate(el => el.getBoundingClientRect().height)
  expect(height).toBeGreaterThanOrEqual(48); expect(height).toBeLessThanOrEqual(60)
  await project.focus(); await expect(project).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('compact-projects.png'), animations: 'disabled' })
  // Render supplied contract data in the authenticated dashboard to exercise
  // long titles, optional previews and overflow without creating fake backend data.
  await page.route('**/api/plugins/chathermes/projects/detail?**', async route => {
    const response = await route.fetch()
    const data = await response.json()
    const sessions = Array.from({ length: 18 }, (_, i) => ({
      id: 'layout-' + i, title: i === 0 ? 'A longer project conversation title that can wrap naturally' : 'Project conversation ' + i,
      ...(i % 2 === 0 ? { preview: 'A supplied preview with enough text to overflow a mobile row and stay on a single line.' } : {}),
      last_active: 20 - i,
    }))
    data.project.repos = [{ id: 'layout', label: 'Layout', groups: [{ id: 'main', label: 'Main', sessions }] }]
    await route.fulfill({ response, json: data })
  })
  await project.click()
  const home = plugin.getByRole('region', { name: 'Selected Project' })
  await expect(home.getByRole('button', { name: 'New chat', exact: true })).toHaveCount(0)
  await expect(home.locator('h3')).toHaveCount(0)
  const rows = home.locator('.project-chat-row')
  await expect(rows).toHaveCount(18)
  await expect(rows.first()).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(rows.first()).toHaveCSS('border-bottom-width', '0px')
  await expect(rows.first()).toHaveCSS('border-radius', '0px')
  await expect(rows.first().locator('.project-chat-preview')).toHaveCSS('white-space', 'nowrap')
  await expect(rows.nth(1).locator('.project-chat-preview')).toHaveCount(0)
  await rows.first().focus(); await expect(rows.first()).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('plain-project-chats.png'), animations: 'disabled' })
  await rows.last().scrollIntoViewIfNeeded(); await expect(rows.last()).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('project-chats-scrolled.png'), animations: 'disabled' })
  await plugin.getByRole('textbox', { name: 'Message Hermes' }).click()
  await expect(plugin.getByRole('textbox', { name: 'Message Hermes' })).toBeFocused()
  await expect(plugin.getByRole('textbox', { name: 'Message Hermes' })).toHaveCSS('font-size', '16px')
  await plugin.getByRole('button', { name: 'Screen options', exact: true }).click()
  await expect(plugin.getByRole('menuitem', { name: 'New chat', exact: true })).toBeEnabled()
  await page.keyboard.press('Escape')
  await expect(plugin.getByRole('button', { name: 'Screen options', exact: true })).toBeFocused()
  expect(await plugin.evaluate(el => el.scrollWidth <= innerWidth)).toBe(true)
})

test('project menu creates an authenticated scoped chat', async ({ page }, testInfo) => {
  await page.setViewportSize(testInfo.project.name === 'mobile' ? { width: 390, height: 844 } : { width: 1280, height: 900 })
  await signIn(page, '/chathermes?view=projects')
  const plugin = page.locator('.chathermes-embedded')
  await plugin.locator('.project-list').getByRole('button', { name: 'Hermes Mobile', exact: true }).click()
  const projectId = new URL(page.url()).searchParams.get('project')
  await plugin.getByRole('button', { name: 'Screen options', exact: true }).click()
  const created = page.waitForResponse(r => r.url().includes('/projects/session?') && r.request().method() === 'POST')
  await plugin.getByRole('menuitem', { name: 'New chat', exact: true }).click()
  const response = await created
  expect(response.status()).toBe(201)
  expect((await response.json()).session.cwd).toBe('/tmp/chathermes-issue7-runtime/workspace-a')
  expect(new URL(page.url()).searchParams.get('project')).toBe(projectId)
  const prompt = plugin.getByRole('textbox', { name: 'Message Hermes' })
  await prompt.click(); await expect(prompt).toBeFocused()
  await prompt.fill('Check project context [tool] [workspace]')
  await plugin.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(plugin.locator('.message.user')).toContainText('Check project context')
  await expect(plugin.locator('.activity[open]').first()).toBeVisible()
  await prompt.click(); await expect(prompt).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('project-menu-chat-active.png') })
  await expect(plugin.locator('.message.assistant').last()).toContainText('Project context discovered.', { timeout: 60_000 })
  await expect(plugin.getByRole('button', { name: 'Send message', exact: true })).toBeVisible()
  await expect(plugin.locator('.activity[open]')).toHaveCount(0)
  await plugin.locator('.work-summary').click()
  const tool = plugin.locator('.activity').filter({ has: page.locator('pre', { hasText: 'terminal' }) })
  await tool.locator('summary').click()
  await expect(tool.locator('pre')).toBeVisible()
  await expect(tool.locator('pre')).toContainText('/tmp/chathermes-issue7-runtime/workspace-a')
  await page.screenshot({ path: testInfo.outputPath('project-menu-chat-completed.png') })
})
