import { expect, test } from '@playwright/test'

test('actual dashboard resumes the same run after reload, accepts guidance and stops from the composer', async ({ page }, info) => {
  await page.goto('/login?next=/chathermes')
  await page.getByLabel('Username').fill('tester')
  await page.getByLabel('Password', { exact: true }).fill('chathermes-local-test')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.chathermes-embedded #prompt')).toBeVisible()
  await page.getByRole('combobox', { name: 'Profile', exact: true }).selectOption('test-profile')
  await expect(page.locator('.chathermes-embedded #prompt')).toBeEnabled()
  await page.locator('.chathermes-embedded #prompt').fill('Keep working for this test [long-run]')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('.message.assistant').last()).toContainText('Isolated Hermes reply')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeVisible()
  const session = new URL(page.url()).searchParams.get('session')!
  expect(session).toBeTruthy()
  await page.reload()
  await expect(page.locator('.chathermes-embedded #prompt')).toBeVisible()
  await expect(page.locator('.message.assistant').last()).toContainText('Isolated Hermes reply')
  await page.screenshot({ path: info.outputPath('resumed-run.png') })
  const composer = page.locator('.composer #prompt')
  await composer.click(); await expect(composer).toBeFocused(); await composer.fill('Draft remains editable')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('.transcript').evaluate(element => getComputedStyle(element).overflowY)).toBe('auto')
  await page.screenshot({ path: info.outputPath('resumed-run.png') })
})
