import { expect, test } from '@playwright/test'

test('actual dashboard resumes the same run after reload, accepts guidance and stops from the composer', async ({ page }, info) => {
  let admissions = 0
  page.on('request', request => { if (/\/v1\/runs(?:\?|$)/.test(request.url()) && request.method() === 'POST') admissions++ })
  await page.goto('/login?next=/chathermes')
  await page.getByLabel('Username').fill('tester')
  await page.getByLabel('Password', { exact: true }).fill('chathermes-local-test')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.chathermes-embedded #prompt')).toBeVisible()
  await page.locator('.chathermes-embedded #prompt').fill('Keep working for this test [long-run]')
  const accepted = page.waitForResponse(response => /\/v1\/runs(?:\?|$)/.test(response.url()) && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  const { run_id } = await (await accepted).json()
  await expect(page.getByRole('button', { name: 'Stop response', exact: true })).toBeEnabled()
  const session = new URL(page.url()).searchParams.get('session')!
  await expect(page.locator('.message.assistant').last()).toContainText('Isolated Hermes reply')
  await page.reload()
  await expect(page.locator('.chathermes-embedded #prompt')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Stop response', exact: true })).toBeEnabled()
  expect(new URL(page.url()).searchParams.get('session')).toBe(session)
  const pointer = await page.evaluate(() => Object.values(localStorage).filter(value => String(value).startsWith('run_')))
  expect(pointer).toContain(run_id)
  await expect(page.locator('.message.assistant')).toHaveCount(1)
  await expect(page.locator('.message.assistant')).toContainText('Isolated Hermes reply')
  expect(admissions).toBe(1)
  const composer = page.locator('.composer #prompt')
  await composer.click(); await expect(composer).toBeFocused(); await composer.fill('Draft remains editable')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('.transcript').evaluate(element => getComputedStyle(element).overflowY)).toBe('auto')
  await page.screenshot({ path: info.outputPath('resumed-run.png') })
  const guidance = page.getByRole('textbox', { name: 'Guide this run', exact: true })
  await guidance.fill('Keep the response concise')
  const steered = page.waitForResponse(response => response.url().includes(`/v1/runs/${run_id}/steer`))
  await page.getByRole('button', { name: 'Send guidance', exact: true }).click()
  expect((await steered).status()).toBe(200)
  const stopping = page.waitForResponse(response => response.url().includes(`/v1/runs/${run_id}/stop`))
  await page.getByRole('button', { name: 'Stop response', exact: true }).click()
  expect((await stopping).status()).toBe(200)
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeVisible({ timeout: 60_000 })
  await expect(composer).toHaveValue('Draft remains editable')
  await page.screenshot({ path: info.outputPath('stopped-run.png') })
  await page.reload()
  await expect(page.locator('.composer #prompt')).toBeVisible()
  expect(admissions).toBe(1)
  await expect(page.locator('.message.user')).toHaveCount(1)
})
