import { signIn } from './login'
import { expect, test } from '@playwright/test'

test('drawer settings, notifications and New chat placement', async ({ page }, testInfo) => {
  const unauthorized = await page.request.get('/api/plugins/chathermes/push/config')
  expect(unauthorized.status()).toBe(401)
  await signIn(page)
  const config = await page.request.get('/api/plugins/chathermes/push/config')
  expect(config.status()).toBe(200)
  const pushConfig = await config.json()
  expect(pushConfig.available).toBe(true)
  expect(pushConfig.vapid_public_key).toHaveLength(87)
  expect(Object.keys(pushConfig).sort()).toEqual(['available', 'vapid_public_key'])
  expect(await (await page.request.get('/api/plugins/chathermes/push/config')).json()).toEqual(pushConfig)
  const worker = await page.request.get('/api/plugins/chathermes/push-service-worker.js')
  expect(worker.status()).toBe(200)
  expect(worker.headers()['service-worker-allowed']).toBe('/chathermes')
  expect(await worker.text()).toContain("addEventListener('push'")
  const manifest = await page.request.get('/api/plugins/chathermes/assets/dist/manifest.webmanifest')
  expect(manifest.status()).toBe(200)
  expect((await manifest.json()).scope).toBe('/chathermes')
  for (const asset of ['apple-touch-icon.png', 'icons/icon-192.png', 'icons/icon-512.png']) {
    const response = await page.request.get('/api/plugins/chathermes/assets/dist/' + asset)
    expect(response.status()).toBe(200)
    expect(response.headers()['content-type']).toContain('image/png')
  }
  const plugin = page.locator('.chathermes-embedded')
  const mobile = testInfo.project.name === 'mobile'
  if (mobile) await plugin.getByRole('button', { name: 'Open navigation' }).click()
  const navigation = plugin.getByRole('complementary', { name: 'Navigation' })
  const newChat = navigation.getByRole('button', { name: 'New chat', exact: true })
  const projects = navigation.getByRole('button', { name: 'Projects', exact: true })
  expect((await projects.boundingBox())!.y).toBeLessThan((await newChat.boundingBox())!.y)
  await expect(navigation.locator('.push-setting')).toHaveCount(0)
  await expect(navigation.getByRole('combobox', { name: 'Profile', exact: true })).toHaveCSS('font-size', '16px')
  const settings = navigation.getByRole('button', { name: 'Settings', exact: true })
  await settings.click()
  const panel = navigation.getByRole('dialog', { name: 'Settings', exact: true })
  await expect(panel).toBeFocused()
  await expect(settings).toHaveAttribute('aria-expanded', 'true')
  await expect(panel.getByRole('button', { name: 'Enable notifications' })).toBeVisible()
  const box = (await panel.boundingBox())!
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.y).toBeGreaterThanOrEqual(0)
  expect(box.y + box.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await page.screenshot({ path: testInfo.outputPath('drawer-settings.png') })
  await page.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(settings).toBeFocused()
  if (mobile) await expect(navigation).toHaveClass(/translate-x-0/)
  await settings.click()
  await panel.getByRole('button', { name: 'Close settings' }).click()
  await expect(settings).toBeFocused()
  await settings.click()
  await projects.click()
  await expect(panel).toHaveCount(0)
  if (mobile) await plugin.getByRole('button', { name: 'Open navigation' }).click()
  await newChat.click()
  if (mobile) await expect(navigation).toHaveClass(/-translate-x-full/)
  const textarea = plugin.getByRole('textbox', { name: 'Message Hermes' })
  await textarea.click()
  await expect(textarea).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('new-chat.png') })
})
