// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import App from './App.vue'
import SessionSidebar from './components/SessionSidebar.vue'
vi.mock('virtual:pwa-register/vue', () => ({ useRegisterSW: () => ({ needRefresh: { value: false }, offlineReady: { value: false }, updateServiceWorker: vi.fn() }) }))
afterEach(() => { vi.unstubAllGlobals(); history.replaceState({}, '', '/') })
const json = (value: unknown) => new Response(JSON.stringify(value), { status: 200, headers: { 'content-type': 'application/json' } })
function deferred<T>() { let resolve!: (value: T) => void, reject!: (reason: Error) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
const profileList = [{ id: 'alpha', label: 'Alpha' }, { id: 'beta', label: 'Beta' }]
const streaming = { features: { session_chat_streaming: true }, endpoints: { session_chat_stream: { method: 'POST', path: '/api/sessions/{session_id}/chat/stream' } } }
describe('profile navigation', () => {
  it('uses Hermes page offsets when pinned sessions are included beyond the limit', async () => {
    const fake = vi.fn(async (input: string) => input === '/api/profiles' ? json(profileList)
      : input.includes('/v1/capabilities') ? json({})
      : input.includes('offset=30') ? json({ object: 'list', data: [{ id: 'pin', title: 'Pinned' }, { id: 'second', title: 'Second page' }], limit: 30, offset: 30, has_more: false })
      : json({ object: 'list', data: [{ id: 'pin', title: 'Pinned' }, { id: 'first', title: 'First page' }], limit: 30, offset: 0, has_more: true }))
    vi.stubGlobal('fetch', fake)
    const wrapper = mount(App)
    await flushPromises()
    await wrapper.get('.load-more').trigger('click')
    await flushPromises()
    expect(fake.mock.calls.some(([input]) => String(input).includes('offset=30'))).toBe(true)
    expect(wrapper.findAll('.session-row')).toHaveLength(3)
    expect(wrapper.text()).toContain('Second page')
    wrapper.unmount()
  })
  it('shows Hermes envelopes and completed stream output in each profile', async () => {
    const fake = vi.fn(async (input: string, init?: RequestInit) => {
      if (input === '/api/profiles') return json(profileList)
      if (input.includes('/v1/capabilities')) return json(streaming)
      const profile = input.includes('/alpha/') ? 'alpha' : 'beta'
      if (input.includes('/chat/stream')) return new Response('event: assistant.delta\ndata: {"delta":"Working","run_id":"run-1"}\n\nevent: tool.started\ndata: {"tool_name":"search","run_id":"run-1"}\n\nevent: run.completed\ndata: {"session_id":"' + profile + '-new","message_id":"msg-1","messages":[],"usage":{},"runtime":{},"run_id":"run-1"}\n\nevent: done\ndata: {}\n\n', { headers: { 'content-type': 'text/event-stream' } })
      if (input.includes('/messages')) return json({ object: 'list', session_id: `${profile}-new`, data: [{ id: `${profile}-user`, role: 'user', content: 'Question' }, { id: `${profile}-reply`, role: 'assistant', content: `Answer from ${profile}` }], pagination: { limit: 500, offset: 0, order: 'oldest', returned: 2 } })
      if (init?.method === 'POST') return json({ object: 'hermes.session', session: { id: `${profile}-new` } })
      if (input.includes('/api/sessions?')) return json({ object: 'list', data: [{ id: `${profile}-new`, title: `${profile} conversation` }], limit: 30, offset: 0, has_more: false })
      return json({})
    })
    vi.stubGlobal('fetch', fake)
    const wrapper = mount(App)
    await flushPromises()
    for (const profile of ['alpha', 'beta']) {
      if (profile === 'beta') await wrapper.get('.profile-picker select').setValue('beta')
      await flushPromises()
      expect(wrapper.text()).toContain(`${profile} conversation`)
      wrapper.findComponent(SessionSidebar).vm.$emit('create')
      await flushPromises()
      expect(location.pathname).toBe(`/p/${profile}/s/${profile}-new`)
      expect(wrapper.text()).toContain(`Answer from ${profile}`)
      await wrapper.get('.composer textarea').setValue('Question')
      await wrapper.get('.composer').trigger('submit')
      await flushPromises()
      expect(wrapper.text()).toContain(`Answer from ${profile}`)
      expect(wrapper.text()).not.toContain('Working…')
      expect(wrapper.text()).not.toContain('Stream ended without confirmation')
    }
    wrapper.unmount()
  })
  it('clears the previous profile sessions when switching', async () => {
    const fake = vi.fn(async (input: string) => {
      const value = input === '/api/profiles' ? [{ id: 'alpha', label: 'Alpha' }, { id: 'beta', label: 'Beta' }]
        : input.includes('/v1/capabilities') ? streaming
        : input.includes('/alpha/api/sessions') ? { sessions: [{ id: 'alpha-one', title: 'Alpha only' }], total: 1 }
        : input.includes('/beta/api/sessions') ? { sessions: [{ id: 'beta-one', title: 'Beta only' }], total: 1 } : {}
      return new Response(JSON.stringify(value), { status: 200, headers: { 'content-type': 'application/json' } })
    })
    vi.stubGlobal('fetch', fake)
    const wrapper = mount(App)
    await flushPromises()
    expect(wrapper.text()).toContain('Alpha only')
    await wrapper.get('.profile-picker select').setValue('beta')
    await flushPromises()
    expect(wrapper.text()).toContain('Beta only')
    expect(wrapper.text()).not.toContain('Alpha only')
    wrapper.unmount()
  })
  it('keeps the session list request alive when a conversation is selected', async () => {
    const list = deferred<Response>()
    const fake = vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? list.promise : Promise.resolve(json({})))
    vi.stubGlobal('fetch', fake)
    const wrapper = mount(App)
    await flushPromises()
    expect(wrapper.text()).toContain('Loading sessions…')
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'shared')
    await flushPromises()
    list.resolve(json({ sessions: [{ id: 'shared', title: 'Still loading' }], total: 1 }))
    await flushPromises()
    expect(wrapper.text()).toContain('Still loading')
    expect(wrapper.text()).not.toContain('Loading sessions…')
    wrapper.unmount()
  })
  it('does not let an older list request clear a newer loading state or show its error', async () => {
    const alpha = deferred<Response>(), beta = deferred<Response>()
    vi.stubGlobal('fetch', vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json({}))
      : input.includes('/alpha/api/sessions?') ? alpha.promise
      : input.includes('/beta/api/sessions?') ? beta.promise : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    await wrapper.get('.profile-picker select').setValue('beta')
    await flushPromises()
    alpha.reject(new Error('Old profile failed'))
    await flushPromises()
    expect(wrapper.text()).toContain('Loading sessions…')
    expect(wrapper.text()).not.toContain('Old profile failed')
    beta.resolve(json({ sessions: [{ id: 'shared', title: 'Beta session' }], total: 1 }))
    await flushPromises()
    expect(wrapper.text()).toContain('Beta session')
    expect(wrapper.text()).not.toContain('Loading sessions…')
    wrapper.unmount()
  })
  it('does not apply a delayed rename to the next profile with the same session ID', async () => {
    const rename = deferred<Response>()
    vi.stubGlobal('fetch', vi.fn((input: string, init?: RequestInit) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json({}))
      : init?.method === 'PATCH' ? rename.promise
      : input.includes('/alpha/api/sessions?') ? Promise.resolve(json({ sessions: [{ id: 'shared', title: 'Alpha title' }], total: 1 }))
      : input.includes('/beta/api/sessions?') ? Promise.resolve(json({ sessions: [{ id: 'shared', title: 'Beta title' }], total: 1 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('rename', 'shared', 'Renamed alpha')
    await wrapper.get('.profile-picker select').setValue('beta')
    await flushPromises()
    rename.resolve(json({ id: 'shared', title: 'Renamed alpha' }))
    await flushPromises()
    expect(wrapper.text()).toContain('Beta title')
    expect(wrapper.text()).not.toContain('Renamed alpha')
    wrapper.unmount()
  })
  it('keeps sending locked after an approval history reload without run completion', async () => {
    let messageLoads = 0
    vi.stubGlobal('fetch', vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [{ id: 'shared', title: 'Conversation' }], total: 1 }))
      : input.includes('/messages') ? (messageLoads++, Promise.resolve(json([])))
      : input.includes('/chat/stream') ? Promise.resolve(new Response('event: approval.request\ndata: {}\n\n', { headers: { 'content-type': 'text/event-stream' } }))
      : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'shared')
    await flushPromises()
    await wrapper.get('.composer textarea').setValue('Please do it')
    await wrapper.get('.composer').trigger('submit')
    await flushPromises()
    expect(wrapper.text()).toContain('Approval is pending')
    expect(wrapper.text()).not.toContain('Working…')
    expect(wrapper.get('.composer textarea').attributes('disabled')).toBeDefined()
    expect(messageLoads).toBe(1)
    await wrapper.get('.notice button').trigger('click')
    await flushPromises()
    expect(messageLoads).toBe(2)
    expect(wrapper.text()).toContain('Approval is pending')
    expect(wrapper.get('.composer textarea').attributes('disabled')).toBeDefined()
    wrapper.unmount()
  })
  it('discards a popstate session when the user switches profile before capabilities return', async () => {
    const betaCapabilities = deferred<Response>()
    vi.stubGlobal('fetch', vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/beta/v1/capabilities') ? betaCapabilities.promise
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [], total: 0 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    history.pushState({}, '', '/p/beta/s/beta-one')
    dispatchEvent(new PopStateEvent('popstate'))
    await flushPromises()
    await wrapper.get('.profile-picker select').setValue('alpha')
    betaCapabilities.resolve(json(streaming))
    await flushPromises()
    expect((wrapper.get('.profile-picker select').element as HTMLSelectElement).value).toBe('alpha')
    expect(wrapper.text()).toContain('Select or create a conversation')
    expect(location.pathname).toBe('/p/alpha')
    wrapper.unmount()
  })
  it('clears unsent text on session and profile changes', async () => {
    vi.stubGlobal('fetch', vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [], total: 0 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'first')
    await flushPromises()
    await wrapper.get('.composer textarea').setValue('secret draft')
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'second')
    await flushPromises()
    expect((wrapper.get('.composer textarea').element as HTMLTextAreaElement).value).toBe('')
    await wrapper.get('.composer textarea').setValue('another draft')
    await wrapper.get('.profile-picker select').setValue('beta')
    expect((wrapper.get('.composer textarea').element as HTMLTextAreaElement).value).toBe('')
    wrapper.unmount()
  })
  it('does not select an in-flight create after a newer session selection or show its stale error', async () => {
    const create = deferred<Response>()
    vi.stubGlobal('fetch', vi.fn((input: string, init?: RequestInit) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : init?.method === 'POST' ? create.promise
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [{ id: 'existing', title: 'Existing' }], total: 1 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('create')
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'existing')
    create.reject(new Error('Stale create failed'))
    await flushPromises()
    expect(location.pathname).toBe('/p/alpha/s/existing')
    expect(wrapper.text()).not.toContain('Stale create failed')
    wrapper.unmount()
  })
  it('does not select a completed create after a newer session selection', async () => {
    const create = deferred<Response>()
    vi.stubGlobal('fetch', vi.fn((input: string, init?: RequestInit) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : init?.method === 'POST' ? create.promise
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [{ id: 'existing', title: 'Existing' }], total: 1 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('create')
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'existing')
    create.resolve(json({ id: 'new' }))
    await flushPromises()
    expect(location.pathname).toBe('/p/alpha/s/existing')
    wrapper.unmount()
  })
  it('allows a successful create to select its new session when selection is unchanged', async () => {
    vi.stubGlobal('fetch', vi.fn((input: string, init?: RequestInit) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/v1/capabilities') ? Promise.resolve(json(streaming))
      : init?.method === 'POST' ? Promise.resolve(json({ id: 'new' }))
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [], total: 0 })) : Promise.resolve(json({}))))
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('create')
    await flushPromises()
    expect(location.pathname).toBe('/p/alpha/s/new')
    wrapper.unmount()
  })
  it('locks sending until the documented streaming capability and endpoint are confirmed', async () => {
    const capabilities = deferred<Response>()
    const fake = vi.fn((input: string) => input === '/api/profiles' ? Promise.resolve(json(profileList))
      : input.includes('/alpha/v1/capabilities') ? capabilities.promise
      : input.includes('/beta/v1/capabilities') ? Promise.resolve(json({ features: { session_chat_streaming: true } }))
      : input.includes('/messages') ? Promise.resolve(json([]))
      : input.includes('/api/sessions?') ? Promise.resolve(json({ sessions: [], total: 0 }))
      : input.includes('/chat/stream') ? Promise.resolve(new Response('event: run.completed\ndata: {}\n\n', { headers: { 'content-type': 'text/event-stream' } })) : Promise.resolve(json({})))
    vi.stubGlobal('fetch', fake)
    const wrapper = mount(App)
    await flushPromises()
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'one')
    await flushPromises()
    expect(wrapper.get('.composer textarea').attributes('disabled')).toBeDefined()
    capabilities.resolve(json(streaming))
    await flushPromises()
    expect(wrapper.get('.composer textarea').attributes('disabled')).toBeUndefined()
    await wrapper.get('.composer textarea').setValue('hello')
    await wrapper.get('.composer').trigger('submit')
    await flushPromises()
    expect(fake.mock.calls.some(([input]) => String(input).includes('/chat/stream'))).toBe(true)
    await wrapper.get('.profile-picker select').setValue('beta')
    wrapper.findComponent(SessionSidebar).vm.$emit('select', 'two')
    await flushPromises()
    expect(wrapper.get('.composer textarea').attributes('disabled')).toBeDefined()
    wrapper.unmount()
  })
})
