// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import App from './App.vue'
import { api } from './lib/hermes-api'
import { projectRoot, projectSessions } from './lib/projects'
import type { Project, ProjectTree } from './types/hermes'
const a: Project = { id: 'p_a', label: 'Project A', path: '/workspace/a', sessionCount: 1, repos: [{ id: 'repo', label: 'Repo', path: '/repo', groups: [{ id: 'worktree', label: 'Outside worktree', path: '/elsewhere/worktree', sessions: [{ id: 'project_s1', title: 'Native worktree chat', cwd: '/elsewhere/worktree', last_active: 3 }] }] }] }
const b: Project = { id: 'p_b', label: 'Project B', sessionCount: 0, repos: [] }
const auto: Project = { ...b, id: '/auto/repo', label: 'Automatic repo', isAuto: true, repos: [{ id: 'repo', label: 'Repo', path: '/auto/repo', groups: [] }] }
const home: Project = { ...b, id: 'home', label: 'Home', isNoProject: true }
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status })
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); history.replaceState({}, '', '/chathermes') })
function setup(detail: (id: string) => Promise<Response> = async id => json({ project: [a, b, auto, home].find(p => p.id === id) })) {
  const fetch = vi.fn(async (url: string, init?: RequestInit) => {
    if (url.includes('/profiles')) return json({ profiles: [{ name: 'alpha' }, { name: 'beta' }] })
    if (url.includes('/projects/session?')) return json({ session: { id: 'project_created', source: 'desktop', cwd: '/workspace/a', workspace_rpc: true } }, 201)
    if (/\/projects(?:\?|$)/.test(url)) return json({ projects: [a, b, auto, home], scoped_session_ids: ['project_s1'] })
    if (url.includes('/projects/')) return detail(new URL(url, 'http://dashboard.test').searchParams.get('project_id')!)
    if (url.includes('/capabilities')) return json({ features: { session_chat_streaming: true }, endpoints: { session_chat_stream: { method: 'POST', path: '/api/sessions/{session_id}/chat/stream' } } })
    if (url.includes('/v1/models')) return json({ data: [] })
    if (url.includes('/model/options')) return json({ providers: [] })
    if (url.includes('/api/sessions/project_created/messages')) return json({}, 404)
    if (url.includes('/messages')) return json({ messages: [{ role: 'assistant', content: 'Native chat history' }] })
    if (url.includes('/chat/stream')) return new Response('event: run.completed\ndata: {}\n\n')
    if (init?.method === 'POST') return json({ session: { id: 'other_created' } }, 201)
    // Deliberately same cwd as A but not claimed by the tree: frontend must not classify it.
    return json({ sessions: [{ id: 's1', title: 'Ungrouped', cwd: a.path }, { id: 'project_s1', title: 'Native worktree chat' }], total: 2 })
  })
  vi.stubGlobal('fetch', fetch)
  return fetch
}
describe('authoritative gateway Projects', () => {
  it.each([{ label: 'populated', rows: [a, b] }, { label: 'empty', rows: [] }])('keeps $label Projects stable during event refreshes', async ({ rows }) => {
    setup(); vi.stubGlobal('EventSource', class {})
    let refresh!: () => void, finish!: (value: ProjectTree) => void
    vi.spyOn(api, 'projectEvents').mockImplementation((_profile, callback) => { refresh = callback; return vi.fn() })
    const read = vi.spyOn(api, 'projects').mockImplementation(() => new Promise(resolve => { finish = resolve }))
    history.replaceState({}, '', '/chathermes?view=projects')
    const wrapper = mount(App); await flushPromises()
    expect(wrapper.get('.projects-page [role="status"]').text()).toBe('Loading Projects…')
    finish({ projects: rows, scoped_session_ids: [] }); await flushPromises()
    expect(wrapper.find('.projects-page [role="status"]').exists()).toBe(false)
    const content = wrapper.get('.projects-page').text(), before = read.mock.calls.length
    refresh(); await new Promise(resolve => setTimeout(resolve, 150)); await flushPromises()
    expect(read.mock.calls.length).toBe(before + 1)
    expect(wrapper.get('.projects-page').text()).toBe(content)
    expect(wrapper.find('.projects-page [role="status"]').exists()).toBe(false)
    finish({ projects: rows, scoped_session_ids: [] }); await flushPromises()
    await wrapper.findAll('.project-tabs button')[1]!.trigger('click'); await flushPromises()
    expect(wrapper.text()).toContain('No archived projects.')
    expect(wrapper.find('.projects-page [role="status"]').exists()).toBe(false)
    finish({ projects: rows, scoped_session_ids: [] }); await flushPromises()
    await wrapper.get('#profile-field').setValue('beta'); await flushPromises()
    await wrapper.get('.projects-nav').trigger('click'); await flushPromises()
    expect(wrapper.get('.projects-page [role="status"]').text()).toBe('Loading Projects…')
    expect(wrapper.find('[aria-label="Project A"]').exists()).toBe(false)
    finish({ projects: [], scoped_session_ids: [] }); await flushPromises()
    expect(wrapper.text()).toContain('No projects yet.')
    wrapper.unmount()
  })
  it('keeps initial loading on retry until Projects have loaded successfully', async () => {
    setup()
    const read = vi.spyOn(api, 'projects').mockRejectedValue(new Error('Unavailable'))
    history.replaceState({}, '', '/chathermes?view=projects')
    const wrapper = mount(App); await flushPromises()
    expect(wrapper.get('.projects-page [role="alert"]').text()).toContain('Could not load Projects.')
    let finish!: (value: ProjectTree) => void
    read.mockImplementation(() => new Promise(resolve => { finish = resolve }))
    await wrapper.get('.projects-page [role="alert"] button').trigger('click'); await flushPromises()
    expect(wrapper.get('.projects-page [role="status"]').text()).toBe('Loading Projects…')
    finish({ projects: [], scoped_session_ids: [] }); await flushPromises()
    expect(wrapper.find('.projects-page [role="status"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('No projects yet.')
    wrapper.unmount()
  })
  it('keeps selected Project content stable while its hierarchy refreshes', async () => {
    setup(); vi.stubGlobal('EventSource', class {})
    let refresh!: () => void, finish!: (value: Project) => void
    vi.spyOn(api, 'projectEvents').mockImplementation((_profile, callback) => { refresh = callback; return vi.fn() })
    vi.spyOn(api, 'project').mockImplementation(() => new Promise(resolve => { finish = resolve }))
    history.replaceState({}, '', '/chathermes?project=p_a')
    const wrapper = mount(App); await flushPromises()
    expect(wrapper.get('[aria-label="Selected Project"] [role="status"]').text()).toBe('Loading Project…')
    finish(a); await flushPromises()
    const content = wrapper.get('[aria-label="Selected Project"]').text()
    refresh(); await new Promise(resolve => setTimeout(resolve, 150)); await flushPromises()
    expect(wrapper.get('[aria-label="Selected Project"]').text()).toBe(content)
    expect(wrapper.find('[aria-label="Selected Project"] [role="status"]').exists()).toBe(false)
    finish(a); await flushPromises()
    wrapper.unmount()
  })
  it('moves Projects out of the drawer and navigates to selected project sessions', async () => {
    const fetch = setup(); const wrapper = mount(App); await flushPromises()
    expect(wrapper.find('.sidebar [aria-label="Project A"]').exists()).toBe(false)
    expect(wrapper.get('.new-chat-nav').text()).toBe('New chat')
    expect(wrapper.find('.drawer-account #profile-field').exists()).toBe(true)
    await wrapper.get('.projects-nav').trigger('click'); await flushPromises()
    expect(wrapper.get('[aria-label="Project list"]').text()).toContain('Automatic repo')
    expect(wrapper.get('[aria-label="Project list"]').text()).not.toContain('Home')
    expect(wrapper.get('[aria-label="Sessions"]').text()).toContain('Ungrouped')
    await wrapper.get('[aria-label="Project A"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[aria-label="Selected Project"]').text()).toContain('Native worktree chat')
    expect(wrapper.get('textarea').attributes('disabled')).toBeUndefined()
    await wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'Native worktree chat')!.trigger('click'); await flushPromises()
    expect(wrapper.text()).toContain('Native chat history')
    expect(location.search).toContain('project=p_a')
    expect(location.search).toContain('session=project_s1')
    expect(api.isWorkspace('', 'project_s1')).toBe(true)
    expect(fetch.mock.calls.some(([url]) => url.includes('/api/sessions/project_s1/messages'))).toBe(true)
    expect(fetch.mock.calls.some(([, init]) => init?.method === 'POST')).toBe(false)
    wrapper.unmount()
  })
  it('retains a workspace project chat context when browsing a separate project', async () => {
    history.replaceState({}, '', '/chathermes?project=p_a&session=project_s1')
    const fetch = setup(); const wrapper = mount(App); await flushPromises()
    await wrapper.get('.projects-nav').trigger('click'); await flushPromises()
    await wrapper.get('[aria-label="Project B"]').trigger('click'); await flushPromises()
    expect(location.search).toContain('session=project_s1')
    expect(location.search).toContain('project=p_b')
    expect(wrapper.get('[aria-label="Selected Project"]').text()).toContain('Project B')
    expect(fetch.mock.calls.some(([, init]) => init?.method === 'POST')).toBe(false)
    wrapper.unmount()
  })
  it('creates a scoped chat and uses the existing composer/runtime interface', async () => {
    history.replaceState({}, '', '/chathermes?profile=alpha&project=p_a')
    const fetch = setup(); const wrapper = mount(App); await flushPromises()
    await wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'New chat')!.trigger('click'); await flushPromises()
    expect(location.search).toContain('session=project_created')
    expect(fetch.mock.calls.find(([url, init]) => url.includes('/projects/session?project_id=p_a') && init?.method === 'POST')).toEqual(expect.arrayContaining(['/api/plugins/chathermes/projects/session?project_id=p_a&profile=alpha', expect.objectContaining({ body: '{}' })]))
    await wrapper.get('textarea').setValue('Check this workspace')
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(fetch.mock.calls.some(([url]) => url.includes('/workspace/sessions/project_created/chat/stream?profile=alpha'))).toBe(true)
    wrapper.unmount()
  })
  it('holds a native draft viewer through the existing event subscription', async () => {
    vi.stubGlobal('EventSource', class {})
    const close = vi.fn()
    const events = vi.spyOn(api, 'projectEvents').mockReturnValue(close)
    setup(); history.replaceState({}, '', '/chathermes?profile=alpha&project=p_a')
    const wrapper = mount(App); await flushPromises()
    await wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'New chat')!.trigger('click'); await flushPromises()
    expect(events).toHaveBeenLastCalledWith('alpha', expect.any(Function), 'project_created')
    wrapper.unmount(); expect(close).toHaveBeenCalled()
  })
  it('ignores a late create after profile changes, and keeps the request pinned to its owner', async () => {
    setup(); let finish!: (value: { id: string }) => void
    const create = vi.spyOn(api, 'projectCreate').mockImplementation(() => new Promise(resolve => { finish = resolve }))
    history.replaceState({}, '', '/chathermes?profile=alpha&project=p_a')
    const wrapper = mount(App); await flushPromises()
    await wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'New chat')!.trigger('click'); await flushPromises()
    await wrapper.get('#profile-field').setValue('beta'); await flushPromises()
    finish({ id: 'late_project_session' }); await flushPromises()
    expect(create).toHaveBeenCalledWith('alpha', 'p_a')
    expect(location.search).toContain('profile=beta')
    expect(location.search).not.toContain('late_project_session')
    wrapper.unmount()
  })
  it('ignores late creation after changing Project scope', async () => {
    setup(); let finish!: (value: { id: string }) => void
    vi.spyOn(api, 'projectCreate').mockImplementation(() => new Promise(resolve => { finish = resolve }))
    history.replaceState({}, '', '/chathermes?project=p_a')
    const wrapper = mount(App); await flushPromises()
    await wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'New chat')!.trigger('click'); await flushPromises()
    await wrapper.get('.projects-nav').trigger('click'); await flushPromises()
    await wrapper.get('[aria-label="Project B"]').trigger('click'); await flushPromises()
    finish({ id: 'late_other_scope' }); await flushPromises()
    expect(location.search).toContain('project=p_b')
    expect(location.search).not.toContain('session=')
    wrapper.unmount()
  })
  it('restores Project scope with a session and browser navigation', async () => {
    history.replaceState({}, '', '/chathermes?project=p_a&session=project_s1&profile=alpha')
    setup(); let wrapper = mount(App); await flushPromises()
    expect(wrapper.text()).toContain('Native chat history'); wrapper.unmount()
    wrapper = mount(App); await flushPromises()
    expect(location.search).toContain('project=p_a')
    history.pushState({}, '', '/chathermes?project=p_b'); dispatchEvent(new PopStateEvent('popstate')); await flushPromises()
    expect(wrapper.get('[aria-label="Selected Project"]').text()).toContain('Project B')
    expect(wrapper.findAll('[aria-label="Selected Project"] button').find(button => button.text() === 'New chat')!.attributes('disabled')).toBeDefined()
    wrapper.unmount()
  })
  it('surfaces deleted/failed Projects and ignores cancelled late reads', async () => {
    history.replaceState({}, '', '/chathermes?project=p_a')
    setup(async () => json({}, 404)); let wrapper = mount(App); await flushPromises()
    expect(wrapper.text()).toContain('Project no longer exists'); wrapper.unmount()
    let finish!: (response: Response) => void
    setup(() => new Promise(resolve => { finish = resolve })); wrapper = mount(App); await flushPromises()
    await wrapper.get('.sidebar > button').trigger('click'); await flushPromises()
    finish(json({ project: a })); await flushPromises()
    expect(wrapper.find('[aria-label="Selected Project"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('refreshes selected hierarchy on gateway events and closes subscription on profile change/unmount', async () => {
    let refresh!: () => void; const close = vi.fn()
    vi.stubGlobal('EventSource', class {})
    const events = vi.spyOn(api, 'projectEvents').mockImplementation((_profile, callback) => { refresh = callback; return close })
    const fetch = setup(); history.replaceState({}, '', '/chathermes?project=p_a&profile=alpha')
    const wrapper = mount(App); await flushPromises()
    const before = fetch.mock.calls.length
    refresh(); await new Promise(resolve => setTimeout(resolve, 150)); await flushPromises()
    expect(fetch.mock.calls.slice(before).some(([url]) => url.includes('/projects/detail?project_id=p_a'))).toBe(true)
    await wrapper.get('#profile-field').setValue('beta'); await flushPromises()
    expect(close).toHaveBeenCalledOnce(); expect(events).toHaveBeenLastCalledWith('beta', expect.any(Function))
    wrapper.unmount(); expect(close).toHaveBeenCalledTimes(2)
  })
  it('uses Project path then first repository path; keeps hierarchy and deduplicates UI rows', () => {
    expect(projectRoot(a)).toBe('/workspace/a'); expect(projectRoot(auto)).toBe('/auto/repo'); expect(projectRoot(home)).toBeUndefined()
    const duplicate = { ...a, repos: [...a.repos, ...a.repos] }
    expect(projectSessions(duplicate)).toHaveLength(1); expect(duplicate.repos).toHaveLength(2)
  })
  it('validates authenticated Project paths and keeps workspace operations profile scoped', async () => {
    const fetch = setup(); await api.projects('alpha'); await api.project('alpha', 'p_a')
    expect(fetch.mock.calls[0]?.[0]).toBe('/api/plugins/chathermes/projects?profile=alpha')
    await expect(api.project('alpha', '../x')).rejects.toThrow('Invalid Hermes Project response')
    await api.project('alpha', '/auto/repo')
    expect(fetch.mock.calls.at(-1)?.[0]).toBe('/api/plugins/chathermes/projects/detail?project_id=%2Fauto%2Frepo&profile=alpha')
    await api.projectCreate('alpha', 'p_a'); await expect(api.messages('beta', 'project_created')).rejects.toMatchObject({ status: 404 })
    expect(fetch.mock.calls.at(-1)?.[0]).toContain('/api/sessions/project_created/messages')
  })
})
